config/routes.rb
Rails.application.routes.draw do

  resources :categories, shallow: true, only: [:show] do
    resources :topics, only: [:new, :create, :edit, :update, :destroy, :show] do
      resources :posts, only: [:new, :create, :edit, :update, :destroy, :show]
    end
  end

  resources :users do
    post :do_verify_email
    get :verify_email
  end
  resource  :session, only: [:index, :new, :create, :show, :destroy]

  root 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_paper_trail

  belongs_to :user
  belongs_to :category

  has_many :posts, dependent: :destroy
  accepts_nested_attributes_for :posts

  validates :name, presence: true, uniqueness: { case_sensitive: false },
            length: { minimum: 5, maximum: 30 }
  validates :user, presence: true
  validates :category, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :load_category, only: [:new, :create]
  def new
    @topic = @category.topics.build
    authorize @topic
    @topic.posts.build
  end

  def create
    @topic = @category.topics.build create_params
    authorize @topic

    @topic.user = current_user
    @topic.posts.first.user = current_user
    @topic.posts.first.topic = @topic

    if @topic.save
      redirect_to @topic
    else
      render :new
    end
  end

  def edit
    @topic = Topic.find params[:id]
    authorize @topic
  end

  def update
    @topic = Topic.find params[:id]
    authorize @topic

    if @topic.update update_params
      redirect_to @topic
    else
      render :edit
    end
  end

  def destroy
    @topic = Topic.find params[:id]
    authorize @topic

    if @topic.destroy
      redirect_to @topic.category
    else
      redirect_to @topic
    end
  end

  def show
    @topic = Topic.find params[:id]
    authorize @topic
  end

  private

  def load_category
    @category = Category.find params[:category_id]
    authorize @category, :show?
  end

  def create_params
    params.require(:topic).permit(:name, posts_attributes: [[:content]])
  end

  def update_params
    params.require(:topic).permit(:name)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_topic.html.haml
.topic
  .header
    %strong= link_to topic.name, topic
    .actions.right.text-right
      Posted by
      = link_to topic.user.name, topic.user
      ,
      = time_ago_in_words(topic.created_at)
      ago
      - unless topic.posts.count < 1
        %br
        = link_to "Last Reply", topic.posts.last
        by
        - user = topic.posts.last.user
        = link_to user.name, user
        = time_ago_in_words(topic.posts.last.created_at)
        ago
  .footer
    %small.left.span
      Created
      = time_ago_in_words(topic.created_at)
      ago

app/views/topics/edit.html.haml
.row
  .columns.small-offset-1.small-10
    = simple_form_for @topic do |f|
      = f.error :base
      = f.input :name
      = f.button :submit

app/views/topics/new.html.haml
.row
  .columns.small-offset-1.small-10
    = simple_form_for [@category, @topic] do |f|
      = f.error :base
      = f.input :name
      = f.simple_fields_for :posts do |p|
        = p.input :content, input_html: {rows: 25}
      = f.button :submit

app/views/topics/show.html.haml
.row
  .columns.small-offset-1.small-10
    %h1=@topic.name
  .columns.small-12
    .right
      - if policy(Post.new topic: @topic).new?
        = link_to "Reply", new_topic_post_path(@topic), class: "button tiny"
      - if policy(@topic).edit?
        = link_to "Edit Topic", edit_topic_path(@topic), class: "button tiny"
  .columns
    - @topic.posts.all.order(created_at: :asc).each do |p|
      .row
        = render p if p.persisted?