config/routes.rb
Rails.application.routes.draw do

  resources :categories, shallow: true, only: [:show] do
    resources :topics, only: [:new, :create, :edit, :update, :destroy, :show] do
      resources :posts, only: [:new, :create, :edit, :update, :destroy, :show]
    end
  end

  resources :users do
    post :do_verify_email
    get :verify_email
  end
  resource  :session, only: [:index, :new, :create, :show, :destroy]

  root 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_paper_trail

  has_many :user_roles, dependent: :destroy
  has_many :roles, -> { distinct }, through: :user_roles

  has_many :sessions
  has_many :mail_tokens

  has_many :topics
  has_many :posts

  validates :email, presence: true, uniqueness: { case_sensitive: false },
            format: { with: /@/ }
  validates :name, presence: true, uniqueness: { case_sensitive: false },
            length: { minimum: 1, maximum: 25 }, format: { with: /\A\S.*\S\z/}
  validates :password, presence: true, on: :create,
            length: { minimum: 2, maximum: 4096 }

  validate :role_length

  before_validation on: :create do
    roles << Role.find_or_create_by(name: "User")
  end

  def can_access? other
    other.roles.empty? or (not (other.roles & self.roles).empty?)
  end

  def has_role_root?
    !roles.find_by_name("root").nil?
  end

  private

  def role_length
    errors.add(:roles, "need to be present") if roles.size < 1
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_logged_in,   only: [:edit, :update, :destroy]
  before_action :check_logged_out,  only: [:new, :create]

  def index
    @users = policy_scope(User).all
  end

  def new
    @user = User.new
    authorize @user
  end

  def create
    @user = User.new create_params

    authorize @user

    if @user.save
      token = @user.mail_tokens.create
      UserMailer.confirmation_mail(token).deliver_now
      flash[:notice] = "We have sent an activation email to you. Please also check your spam folder for overzealous filters."
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])

    authorize @user
  end

  def edit
    @user = User.find(params[:id])

    authorize @user
  end

  def update
    @user = User.find(params[:id])

    authorize @user

    if @user.update_attributes update_params
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])

    authorize @user

    if @user.destroy
      redirect_to root_path
    else
      redirect_to user_path(@user)
    end
  end

  def verify_email
    @token = MailToken.where('valid_until > ?', DateTime.now).find_by_token!(params['token'])
    @user = @token.user

    skip_authorization
  end

  def do_verify_email
    @token = MailToken.where('valid_until > ?', DateTime.now).find_by_token!(params['token'])
    @user = @token.user

    skip_authorization

    @user.verified_email = true
    @user.save

    @token.destroy

    redirect_to new_session_path

  end

  private

  def create_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def update_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

  def check_logged_in
    redirect_to new_session_path unless current_user
  end

  def check_logged_out
    redirect_to user_path(current_user) if current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    @__current_user ||= Session.find_by_id(session[:sess_id]).try!(:user)
  end

  def logged_in?
    !current_user.nil?
  end
end

app/views/users/_user.html.haml
.panel
  %a.th{href: user_path(user)}
    %img{src: "https://placehold.it/50/ffffff/50", height: 50, width: 50}

  %a{href: user_path(user)}
    = user.name

app/views/users/edit.html.haml
.row
  .columns.small-offset-1.small-10
    = simple_form_for @user do |f|
      = f.error :base
      = f.input :name
      = f.input :email, disabled: true
      = f.input :password, required: false
      = f.input :password_confirmation
      = f.button :submit

app/views/users/index.html.haml
.row
  .columns.small-12.medium-offset-1.medium-10
    - @users.each do |u|
      .row
        .small-12
          = render u

app/views/users/new.html.haml
.row
  .columns.small-offset-1.small-10
    = simple_form_for @user do |f|
      = f.error :base
      = f.input :name
      = f.input :email
      = f.input :password
      = f.input :password_confirmation
      = f.button :submit

app/views/users/show.html.haml
.row
  .columns.small-12.user-info
    %a.th.left.avatar-container
      = image_tag "https://placehold.it/200/ffffff/200"
    %h1= @user.name
    - if UserPolicy.new(@user, @user).update? # TODO: Get RSpec and Pundit working together
      .panel.right
        = link_to "Edit Profile", edit_user_path(@user)

app/views/users/verify_email.html.haml
.row
  .columns.small-offset-1.small-10
    = form_tag user_do_verify_email_path(@user), method: "POST" do |f|
      = label_tag :token, "Verification Token:"
      = text_field_tag :token, @token.try!(:token)
      = submit_tag "Verify EMail"