config/routes.rb
Rails.application.routes.draw do

  resources :categories, shallow: true, only: [:show] do
    resources :topics, only: [:new, :create, :edit, :update, :destroy, :show] do
      resources :posts, only: [:new, :create, :edit, :update, :destroy, :show]
    end
  end

  resources :users do
    post :do_verify_email
    get :verify_email
  end
  resource  :session, only: [:index, :new, :create, :show, :destroy]

  root 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_roles
  has_many :roles, through: :category_roles

  has_many :topics

  validates :name, uniqueness: { case_sensitive: true }

  def can_be_accessed_by? other
    self.roles.empty? || (other && other.can_access?(self))
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    authorize @category
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.haml
.category
  .category-header
    %h2
      = link_to category.name, category
      - if policy(Topic.new category: category).new?
        .right
          = link_to "New Topic", new_category_topic_path(category), class: "new-topic"

      - unless category.roles.empty?
        %span.label.info.right
          .has-tip{:'data-tooltip' => true, :'aria-haspopup' => true,
                   title: "Visible for: " + category.roles.map{|x| x.name}.join(',')}
            Visiblity
  .row.topic-rows
    .column.small-12
      = render category.topics.limit 5

app/views/categories/show.html.haml
.row
  .columns.small-12.category-info
    %h1= @category.name
    - if policy(Topic.new category: @category).new?
      .right
        %ul.button-group
          %li= link_to "New Topic", new_category_topic_path(@category), class: "button tiny"
.row
  .columns.small-12.topics-list
    - @category.topics.each do |t|
      .row
        .columns.small-12
          = render t