config/routes.rb
Rails.application.routes.draw do

  resources :categories, shallow: true, only: [:show] do
    resources :topics, only: [:new, :create, :edit, :update, :destroy, :show] do
      resources :posts, only: [:new, :create, :edit, :update, :destroy, :show]
    end
  end

  resources :users do
    post :do_verify_email
    get :verify_email
  end
  resource  :session, only: [:index, :new, :create, :show, :destroy]

  root 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_roles
  has_many :roles, through: :category_roles

  has_many :topics

  validates :name, uniqueness: { case_sensitive: true }

  def can_be_accessed_by? other
    self.roles.empty? || (other && other.can_access?(self))
  end
end

app/models/category_role.rb
class CategoryRole < ActiveRecord::Base
  belongs_to :role
  belongs_to :category
end

app/models/mail_token.rb
class MailToken < ActiveRecord::Base
  belongs_to :user

  before_create on: :create do
    self.token = SecureRandom.hex 32
    self.valid_until = 1.day.from_now
  end

  def valid_token_at? date
    date < self.valid_until
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic, counter_cache: true


  validates :content, presence: true, length: { maximum: 100_000 }

  def anchor
    "post_#{id}"
  end

  def position
    topic.posts.where('created_at <= ?', created_at).count
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  validates :name, uniqueness: { case_sensitive: true }
end

app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :user

  default_scope { where('created_at > ?' , 7.days.ago) }

  validates :ip, presence: true

  def active?
    created_at > 7.days.ago
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_paper_trail

  belongs_to :user
  belongs_to :category

  has_many :posts, dependent: :destroy
  accepts_nested_attributes_for :posts

  validates :name, presence: true, uniqueness: { case_sensitive: false },
            length: { minimum: 5, maximum: 30 }
  validates :user, presence: true
  validates :category, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_paper_trail

  has_many :user_roles, dependent: :destroy
  has_many :roles, -> { distinct }, through: :user_roles

  has_many :sessions
  has_many :mail_tokens

  has_many :topics
  has_many :posts

  validates :email, presence: true, uniqueness: { case_sensitive: false },
            format: { with: /@/ }
  validates :name, presence: true, uniqueness: { case_sensitive: false },
            length: { minimum: 1, maximum: 25 }, format: { with: /\A\S.*\S\z/}
  validates :password, presence: true, on: :create,
            length: { minimum: 2, maximum: 4096 }

  validate :role_length

  before_validation on: :create do
    roles << Role.find_or_create_by(name: "User")
  end

  def can_access? other
    other.roles.empty? or (not (other.roles & self.roles).empty?)
  end

  def has_role_root?
    !roles.find_by_name("root").nil?
  end

  private

  def role_length
    errors.add(:roles, "need to be present") if roles.size < 1
  end
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @categories = policy_scope(Category.all)
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_action :load_topic, only: [:new, :create]
  def new
    @post = @topic.posts.build
    authorize @post
  end

  def create
    @post = @topic.posts.build create_params
    authorize @post

    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    authorize @post

    if @post.update(update_params)
      redirect_to topic_path(@post.topic, anchor: @post.anchor)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize @post

    @post.destroy
  end

  def show
    @post = Post.find(params[:id])
    authorize @post

    redirect_to topic_path(@post.topic, anchor: @post.anchor)
  end

  private

  def create_params
    params.require(:post).permit(:content, :type)
  end

  def update_params
    params.require(:post).permit(:content)
  end

  def load_topic
    @topic = Topic.find(params[:topic_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_topic, only: [:new, :create]
  def new
    @post = @topic.posts.build
    authorize @post
  end

  def create
    @post = @topic.posts.build create_params
    authorize @post
    @post.user = current_user

    if @post.save
      redirect_to @post
    else
      byebug
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    authorize @post

    if @post.update(update_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize @post

    @post.destroy
  end

  def show
    @post = Post.find(params[:id])
    authorize @post

    redirect_to topic_path(@post.topic, anchor: @post.anchor)
  end

  private

  def create_params
    params.require(:post).permit(:content, :type)
  end

  def update_params
    params.require(:post).permit(:content)
  end

  def load_topic
    @topic = Topic.find(params[:topic_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pundit
  def markdown(text)
    options = {no_intra_emphasis: true, tables: true,
               fenced_code_blocks: true, disable_indented_code_block: true,
               strikethrough: true, superscript: true, underline: true,
               footnotes: true, hard_wrap: true, safe_links_only: true,
               escape_html: true, link_attributes: {rel:"nofollow", target:"_blank"}}
    renderer = TwrRenderer.new(options)
    Redcarpet::Markdown.new(renderer, options).render(text.freeze).html_safe
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topbar_helper.rb
module TopbarHelper
  def topbar_link_to link, content, opts={}
    opts[:href] = link
    content_tag(:li, content_tag(:a, content, opts),
                class: [(:active if (current_page?(link) && !opts[:'no-highlight']))])
  end

  def topbar_dropdown link, content, &block
    content_tag(:li,
                content_tag(:a, content, href: link) +
                content_tag(:ul, capture(&block), class:['dropdown']),
                class: ['has-dropdown'])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    @__current_user ||= Session.find_by_id(session[:sess_id]).try!(:user)
  end

  def logged_in?
    !current_user.nil?
  end
end

app/views/common/_topbar.html.haml
%nav#navbar.top-bar{'data-topbar' => true, role: 'navigation',
                    :'data-options' => "is_hover: false",
                    'data-turbolinks-permanent' => true}
  %ul.title-area
    %li.name
      %h1
        %a{href: root_path} The Wyvern Rocks

  %section.top-bar-section
    %ul.right
      - if logged_in?
        = topbar_dropdown user_path(current_user), current_user.name do
          = topbar_link_to users_path, "Users"
          = topbar_link_to session_path, "Sessions"
          = topbar_link_to session_path, "Log out", :'data-method' => "DELETE", :'no-highlight' => true
      - else
        = topbar_dropdown new_user_path, "Register" do
          = topbar_link_to new_session_path, "Sign in"

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en"}
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tag

  %body
    = render 'common/topbar'

    #content
      .panel.callout.radius
        %p
          Welcome to
          %em The Wyvern Rocks
          \! We are a young community, just on the verge of starting up.
          It is pre-alpha, this means not everything will always work
          all the time. However, steady progress will transform this into
          something great. Hold tight and let's cruise through these uncharted
          waters together!
        %p
          If you do find any bugs, please report them per email,
          to
          %em neikos at neikos dot email
          or on
          %a{href: "https://github.com/theneikos/the.wyvern.rocks/issues/new"}
            Github
          \. You can also post them into the Bug Reporting Station in the Forums.
      - if not flash[:notice].nil? then
        .row
          .columns.small-12
            .alert-box.info
              = flash[:notice]
              %a{href: '#', class:'close'} &times;
      - if not flash[:alert].nil? then
        .row
          .columns.small-12
            .alert-box.alert
              = flash[:alert]
              %a{href: '#', class:'close'} &times;
      = yield

  %footer
    %p.text-center
      %small
        &copy; The Wyvern Rocks
        = Time.now.year
        \-
        %em
          Server Time is
          = Time.now
        %br
        Built with &#9829; in Europe using
        %a{href:"https://www.gnu.org/"}
          Free/Libre Software
        hosted on
        %a{href:"https://github.com"}
          Github